from extra.figures import Figure, Direction
from config import Paths
import os

IMGS = [
    "board1.jpg",
    "board2.jpg",
    "board3.jpg",
    "board4.jpg",
    "board5.jpg",
    # "board6.jpg",
    # "board7.jpg",
    # "board8.jpg",
    # "board9.jpg",
    # "board10.jpg",
    # "board11.jpg",
    # "board12.jpg",
    "board13.jpg",
    "board14.jpg",
    "board15.jpg",
    "board16.jpg",
    "board17.jpg",
    "board18.jpg",
    "board19.jpg",
    "board20.jpg",
    "board21.jpg",
    "board22.jpg",
    "board23.jpg",
    "board24.jpg",
    "board25.jpg",
    "board26.jpg",
    "board27.jpg",
    "board28.jpg",
    "board29.jpg",
    "board30.jpg",
    "board31.jpg",
    "board32.jpg",
    "board33.jpg",
    "board34.jpg",
    "board35.jpg",
    "board36.jpg",
    "board37.jpg",
    "board38.jpg",
    "board39.jpg",
    "board40.jpg",
    "board41.jpg",
    "board42.jpg",
    "board43.jpg",
    "board44.jpg",
    "board45.jpg",
    "board46.jpg",
    "board47.jpg",
    "board48.jpg",
    "board49.jpg",
    "board50.jpg",
    "board51.jpg",
    "board52.jpg",
    "board53.jpg",
    "board54.jpg",
    "board55.jpg",
    "board56.jpg",
    "board57.jpg",
    "board58.jpg",
    "board59.jpg",
    "board60.jpg",
    "board61.jpg",
    "board62.jpg",
    "board63.jpg",
    "board64.jpg",
    "board65.jpg",
    "board66.jpg",
    "board67.jpg",
    "board68.jpg",
]

CATEGORIES_FIGURE_TYPE = [
    Figure.PAWN,
    Figure.BISHOP,
    Figure.ROOK,
    Figure.LANCE,
    Figure.KNIGHT,
    Figure.SILVER,
    Figure.GOLD,
    Figure.KING,
    Figure.EMPTY,

    Figure.PAWN_PROM,
    Figure.LANCE_PROM,
    Figure.KNIGHT_PROM,
    Figure.SILVER_PROM,
    Figure.BISHOP_PROM,
    Figure.ROOK_PROM
]

CATEGORIES_DIRECTION = [Direction.UP, Direction.DOWN, Direction.NONE]
