pyuic5 create_dataset.ui > create_dataset.py
pyuic5 scan_image.ui > UI_scan_image.py
pyuic5 scan_book.ui > UI_scan_book.py
pyuic5 DescriptiveComboBox.ui > UI_DescriptiveComboBox.py
pyuic5 VisualCornerSelect.ui > UI_VisualCornerSelect.py
pyuic5 BoardView.ui > UI_BoardView.py
pyuic5 ProgressWorker.ui > UI_ProgressWorker.py
pyuic5 KifRecorder.ui > UI_KifRecorder.py
pyuic5 FileDragDrop.ui > UI_FileDragDrop.py
pyuic5 ShogiVision.ui > UI_ShogiVision.py
