pyuic5 create_dataset.ui > create_dataset.py
pyuic5 ScanImage.ui > UI_ScanImage.py
pyuic5 Settings.ui > UI_Settings.py
pyuic5 scan_book.ui > UI_scan_book.py
pyuic5 DescriptiveComboBox.ui > UI_DescriptiveComboBox.py
pyuic5 DetectorsSelect.ui > UI_DetectorsSelect.py
pyuic5 BoardView.ui > UI_BoardView.py
pyuic5 ProgressWorker.ui > UI_ProgressWorker.py
pyuic5 KifRecorder.ui > UI_KifRecorder.py
pyuic5 FileDragDrop.ui > UI_FileDragDrop.py
pyuic5 ShogiVision.ui > UI_ShogiVision.py
