# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scan_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.detector_select = DetectorSelect(self.frame)
        self.detector_select.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detector_select.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detector_select.setObjectName("detector_select")
        self.verticalLayout.addWidget(self.detector_select)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_inventory_detector = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_inventory_detector.setObjectName("comboBox_inventory_detector")
        self.comboBox_inventory_detector.addItem("")
        self.comboBox_inventory_detector.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_inventory_detector)
        self.verticalLayout.addWidget(self.frame_5)
        self.pushButton_clipboard = QtWidgets.QPushButton(self.frame)
        self.pushButton_clipboard.setObjectName("pushButton_clipboard")
        self.verticalLayout.addWidget(self.pushButton_clipboard)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_predicted_board = ImageLabel(self.frame_2)
        self.label_predicted_board.setObjectName("label_predicted_board")
        self.verticalLayout_2.addWidget(self.label_predicted_board)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.textEdit_sfen = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_sfen.setObjectName("textEdit_sfen")
        self.verticalLayout_3.addWidget(self.textEdit_sfen)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.pushButton_to_lishogi = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_to_lishogi.setObjectName("pushButton_to_lishogi")
        self.verticalLayout_4.addWidget(self.pushButton_to_lishogi)
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "InventoryDetector:"))
        self.comboBox_inventory_detector.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_inventory_detector.setItemText(1, _translate("MainWindow", "Book"))
        self.pushButton_clipboard.setText(_translate("MainWindow", "From clipboard"))
        self.label_predicted_board.setText(_translate("MainWindow", "PredictedBoard"))
        self.label.setText(_translate("MainWindow", "SFEN:"))
        self.pushButton_to_lishogi.setText(_translate("MainWindow", "To lishogi"))
from GUI.components.DetectorSelect import DetectorSelect
from GUI.components.ImageLabel import ImageLabel
