# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DetectorsSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_visualCornerSelect(object):
    def setupUi(self, visualCornerSelect):
        visualCornerSelect.setObjectName("visualCornerSelect")
        visualCornerSelect.resize(786, 359)
        self.verticalLayout = QtWidgets.QVBoxLayout(visualCornerSelect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(visualCornerSelect)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label_original = ImageLabel(self.frame_2)
        self.image_label_original.setObjectName("image_label_original")
        self.horizontalLayout.addWidget(self.image_label_original)
        self.image_label_no_perspective = ImageLabel(self.frame_2)
        self.image_label_no_perspective.setObjectName("image_label_no_perspective")
        self.horizontalLayout.addWidget(self.image_label_no_perspective)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_selects = QtWidgets.QFrame(visualCornerSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_selects.sizePolicy().hasHeightForWidth())
        self.frame_selects.setSizePolicy(sizePolicy)
        self.frame_selects.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selects.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selects.setObjectName("frame_selects")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_selects)
        self.gridLayout.setObjectName("gridLayout")
        self.corner_detector_select = DescriptiveComboBox(self.frame_selects)
        self.corner_detector_select.setObjectName("corner_detector_select")
        self.gridLayout.addWidget(self.corner_detector_select, 0, 0, 1, 1)
        self.inventory_detector_select = DescriptiveComboBox(self.frame_selects)
        self.inventory_detector_select.setObjectName("inventory_detector_select")
        self.gridLayout.addWidget(self.inventory_detector_select, 0, 1, 1, 1)
        self.label_click_corners = QtWidgets.QLabel(self.frame_selects)
        self.label_click_corners.setStyleSheet("color: rgb(46, 194, 126);")
        self.label_click_corners.setAlignment(QtCore.Qt.AlignCenter)
        self.label_click_corners.setObjectName("label_click_corners")
        self.gridLayout.addWidget(self.label_click_corners, 2, 0, 1, 1)
        self.pushButton_set_corners = QtWidgets.QPushButton(self.frame_selects)
        self.pushButton_set_corners.setObjectName("pushButton_set_corners")
        self.gridLayout.addWidget(self.pushButton_set_corners, 1, 0, 1, 1)
        self.checkBox_show_borders = QtWidgets.QCheckBox(self.frame_selects)
        self.checkBox_show_borders.setObjectName("checkBox_show_borders")
        self.gridLayout.addWidget(self.checkBox_show_borders, 0, 2, 1, 1)
        self.checkBox_show_grid = QtWidgets.QCheckBox(self.frame_selects)
        self.checkBox_show_grid.setObjectName("checkBox_show_grid")
        self.gridLayout.addWidget(self.checkBox_show_grid, 1, 2, 1, 1)
        self.checkBox_show_inventories = QtWidgets.QCheckBox(self.frame_selects)
        self.checkBox_show_inventories.setObjectName("checkBox_show_inventories")
        self.gridLayout.addWidget(self.checkBox_show_inventories, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_selects, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(visualCornerSelect)
        self.image_label_original.clicked.connect(visualCornerSelect.on_image_clicked) # type: ignore
        self.pushButton_set_corners.clicked.connect(visualCornerSelect.on_set_corners_clicked) # type: ignore
        self.corner_detector_select.element_changed['QVariant'].connect(visualCornerSelect.on_corner_detector_changed) # type: ignore
        self.inventory_detector_select.element_changed['QVariant'].connect(visualCornerSelect.on_inventory_detector_changed) # type: ignore
        self.checkBox_show_borders.clicked['bool'].connect(visualCornerSelect.on_show_borders_switched) # type: ignore
        self.checkBox_show_grid.clicked['bool'].connect(visualCornerSelect.on_show_grid_switched) # type: ignore
        self.checkBox_show_inventories.clicked['bool'].connect(visualCornerSelect.on_show_inventories_switched) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(visualCornerSelect)

    def retranslateUi(self, visualCornerSelect):
        _translate = QtCore.QCoreApplication.translate
        visualCornerSelect.setWindowTitle(_translate("visualCornerSelect", "visualCornerSelect"))
        self.image_label_original.setText(_translate("visualCornerSelect", "Image"))
        self.image_label_no_perspective.setText(_translate("visualCornerSelect", "Image"))
        self.label_click_corners.setText(_translate("visualCornerSelect", "Now click 4 corners on left image"))
        self.pushButton_set_corners.setText(_translate("visualCornerSelect", "Set Corners"))
        self.checkBox_show_borders.setText(_translate("visualCornerSelect", "Show borders"))
        self.checkBox_show_grid.setText(_translate("visualCornerSelect", "Show grid"))
        self.checkBox_show_inventories.setText(_translate("visualCornerSelect", "Show inventories"))
from GUI.widgets.DescriptiveComboBox import DescriptiveComboBox
from GUI.widgets.ImageLabel import ImageLabel
