# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DescriptiveComboBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_descriptiveComboBox(object):
    def setupUi(self, descriptiveComboBox):
        descriptiveComboBox.setObjectName("descriptiveComboBox")
        descriptiveComboBox.resize(326, 79)
        font = QtGui.QFont()
        font.setPointSize(11)
        descriptiveComboBox.setFont(font)
        self.formLayout = QtWidgets.QFormLayout(descriptiveComboBox)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(descriptiveComboBox)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.comboBox = QtWidgets.QComboBox(descriptiveComboBox)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_description = QtWidgets.QLabel(descriptiveComboBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_description)

        self.retranslateUi(descriptiveComboBox)
        self.comboBox.currentIndexChanged['int'].connect(descriptiveComboBox.on_element_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(descriptiveComboBox)

    def retranslateUi(self, descriptiveComboBox):
        _translate = QtCore.QCoreApplication.translate
        descriptiveComboBox.setWindowTitle(_translate("descriptiveComboBox", "DescriptiveComboBox"))
        self.label_name.setText(_translate("descriptiveComboBox", "Name:"))
        self.label_description.setText(_translate("descriptiveComboBox", "Description:"))
