# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileDragDrop.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fileDragDrop(object):
    def setupUi(self, fileDragDrop):
        fileDragDrop.setObjectName("fileDragDrop")
        fileDragDrop.resize(392, 99)
        self.verticalLayout = QtWidgets.QVBoxLayout(fileDragDrop)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(fileDragDrop)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(fileDragDrop)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(fileDragDrop)
        self.pushButton.clicked.connect(fileDragDrop.on_paste_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(fileDragDrop)

    def retranslateUi(self, fileDragDrop):
        _translate = QtCore.QCoreApplication.translate
        fileDragDrop.setWindowTitle(_translate("fileDragDrop", "FileDragDrop"))
        self.label.setText(_translate("fileDragDrop", "Drag & drop file here or paste it from clipboard"))
        self.pushButton.setText(_translate("fileDragDrop", "Paste from clipboard"))
