# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KifRecorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kifRecorder(object):
    def setupUi(self, kifRecorder):
        kifRecorder.setObjectName("kifRecorder")
        kifRecorder.resize(404, 396)
        self.verticalLayout = QtWidgets.QVBoxLayout(kifRecorder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_kif = QtWidgets.QTextEdit(kifRecorder)
        self.textEdit_kif.setObjectName("textEdit_kif")
        self.verticalLayout.addWidget(self.textEdit_kif)
        self.pushButton_copy_kif = QtWidgets.QPushButton(kifRecorder)
        self.pushButton_copy_kif.setObjectName("pushButton_copy_kif")
        self.verticalLayout.addWidget(self.pushButton_copy_kif)

        self.retranslateUi(kifRecorder)
        self.pushButton_copy_kif.clicked.connect(kifRecorder.on_copy_kif_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(kifRecorder)

    def retranslateUi(self, kifRecorder):
        _translate = QtCore.QCoreApplication.translate
        kifRecorder.setWindowTitle(_translate("kifRecorder", "KifRecorder"))
        self.pushButton_copy_kif.setText(_translate("kifRecorder", "Copy KIF"))
