# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scan_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scan_book(object):
    def setupUi(self, scan_book):
        scan_book.setObjectName("scan_book")
        scan_book.resize(713, 518)
        self.horizontalLayout = QtWidgets.QHBoxLayout(scan_book)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(scan_book)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget_pageBoards = QtWidgets.QListWidget(self.frame)
        self.listWidget_pageBoards.setObjectName("listWidget_pageBoards")
        self.verticalLayout_2.addWidget(self.listWidget_pageBoards)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_previous = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.horizontalLayout_2.addWidget(self.pushButton_previous)
        self.label_page = QtWidgets.QLabel(self.frame_3)
        self.label_page.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page.setObjectName("label_page")
        self.horizontalLayout_2.addWidget(self.label_page)
        self.pushButton_next = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_2.addWidget(self.pushButton_next)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(scan_book)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.board_view = BoardView(self.frame_2)
        self.board_view.setObjectName("board_view")
        self.verticalLayout.addWidget(self.board_view)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(scan_book)
        self.pushButton_previous.clicked.connect(scan_book.on_previous_clicked) # type: ignore
        self.pushButton_next.clicked.connect(scan_book.on_next_clicked) # type: ignore
        self.listWidget_pageBoards.itemSelectionChanged.connect(scan_book.on_board_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(scan_book)

    def retranslateUi(self, scan_book):
        _translate = QtCore.QCoreApplication.translate
        scan_book.setWindowTitle(_translate("scan_book", "scan_book"))
        self.label.setText(_translate("scan_book", "Drag & Drop PDF file here"))
        self.pushButton_previous.setText(_translate("scan_book", "Previous"))
        self.label_page.setText(_translate("scan_book", "Page"))
        self.pushButton_next.setText(_translate("scan_book", "Next"))
from GUI.components.BoardView import BoardView
