# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(1281, 583)
        self.horizontalLayout = QtWidgets.QHBoxLayout(settings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_getter_select = DescriptiveComboBox(self.groupBox)
        self.image_getter_select.setObjectName("image_getter_select")
        self.verticalLayout_2.addWidget(self.image_getter_select)
        self.cam_id_select = DescriptiveComboBox(self.groupBox)
        self.cam_id_select.setObjectName("cam_id_select")
        self.verticalLayout_2.addWidget(self.cam_id_select)
        self.pushButton_upload_file = UploadFileButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_upload_file.setFont(font)
        self.pushButton_upload_file.setObjectName("pushButton_upload_file")
        self.verticalLayout_2.addWidget(self.pushButton_upload_file)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_memorizer = QtWidgets.QGroupBox(self.frame)
        self.groupBox_memorizer.setObjectName("groupBox_memorizer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_memorizer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.memorizer_select = DescriptiveComboBox(self.groupBox_memorizer)
        self.memorizer_select.setObjectName("memorizer_select")
        self.verticalLayout.addWidget(self.memorizer_select)
        self.checkBox_lower_moves_first = QtWidgets.QCheckBox(self.groupBox_memorizer)
        self.checkBox_lower_moves_first.setChecked(True)
        self.checkBox_lower_moves_first.setObjectName("checkBox_lower_moves_first")
        self.verticalLayout.addWidget(self.checkBox_lower_moves_first)
        self.checkBox_siren = QtWidgets.QCheckBox(self.groupBox_memorizer)
        self.checkBox_siren.setStyleSheet("color: rgb(224, 27, 36);")
        self.checkBox_siren.setObjectName("checkBox_siren")
        self.verticalLayout.addWidget(self.checkBox_siren)
        self.verticalLayout_6.addWidget(self.groupBox_memorizer)
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout_6.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout_6.addWidget(self.pushButton_cancel)
        self.horizontalLayout.addWidget(self.frame)
        self.corner_and_inventory_select = DetectorsSelect(settings)
        self.corner_and_inventory_select.setObjectName("corner_and_inventory_select")
        self.horizontalLayout.addWidget(self.corner_and_inventory_select)

        self.retranslateUi(settings)
        self.image_getter_select.element_changed['QVariant'].connect(settings.on_image_getter_changed) # type: ignore
        self.corner_and_inventory_select.splitter_changed['QVariant'].connect(settings.on_splitter_changed) # type: ignore
        self.checkBox_lower_moves_first.clicked['bool'].connect(settings.on_lower_moves_first_switched) # type: ignore
        self.cam_id_select.element_changed['QVariant'].connect(settings.on_cam_id_changed) # type: ignore
        self.checkBox_siren.clicked['bool'].connect(settings.on_alarm_switched) # type: ignore
        self.pushButton_ok.clicked.connect(settings.on_ok_clicked) # type: ignore
        self.pushButton_cancel.clicked.connect(settings.on_cancel_clicked) # type: ignore
        self.memorizer_select.element_changed['QVariant'].connect(settings.on_memorizer_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Settings"))
        self.groupBox.setTitle(_translate("settings", "Select image"))
        self.pushButton_upload_file.setText(_translate("settings", "Upload Files"))
        self.groupBox_memorizer.setTitle(_translate("settings", "Board memorizer"))
        self.checkBox_lower_moves_first.setText(_translate("settings", "Lower moves  first"))
        self.checkBox_siren.setText(_translate("settings", "Use siren (LOUD)"))
        self.pushButton_ok.setText(_translate("settings", "OK"))
        self.pushButton_cancel.setText(_translate("settings", "Cancel"))
from GUI.widgets.DescriptiveComboBox import DescriptiveComboBox
from GUI.widgets.DetectorsSelect import DetectorsSelect
from GUI.widgets.UploadFileButton import UploadFileButton
