# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(1281, 583)
        self.horizontalLayout = QtWidgets.QHBoxLayout(settings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_images_select = QtWidgets.QFrame(self.frame)
        self.frame_images_select.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_images_select.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_images_select.setObjectName("frame_images_select")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_images_select)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_getter_select = DescriptiveComboBox(self.frame_images_select)
        self.image_getter_select.setObjectName("image_getter_select")
        self.verticalLayout_3.addWidget(self.image_getter_select)
        self.photo_drop = FileDragDrop(self.frame_images_select)
        self.photo_drop.setObjectName("photo_drop")
        self.verticalLayout_3.addWidget(self.photo_drop)
        self.video_drop = FileDragDrop(self.frame_images_select)
        self.video_drop.setObjectName("video_drop")
        self.verticalLayout_3.addWidget(self.video_drop)
        self.cam_id_select = DescriptiveComboBox(self.frame_images_select)
        self.cam_id_select.setObjectName("cam_id_select")
        self.verticalLayout_3.addWidget(self.cam_id_select)
        self.verticalLayout_6.addWidget(self.frame_images_select)
        self.frame_memorizer = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_memorizer.sizePolicy().hasHeightForWidth())
        self.frame_memorizer.setSizePolicy(sizePolicy)
        self.frame_memorizer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_memorizer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_memorizer.setObjectName("frame_memorizer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_memorizer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_memorizer)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.memorizer_select = DescriptiveComboBox(self.frame_memorizer)
        self.memorizer_select.setObjectName("memorizer_select")
        self.verticalLayout_4.addWidget(self.memorizer_select)
        self.checkBox_lower_moves_first = QtWidgets.QCheckBox(self.frame_memorizer)
        self.checkBox_lower_moves_first.setChecked(True)
        self.checkBox_lower_moves_first.setObjectName("checkBox_lower_moves_first")
        self.verticalLayout_4.addWidget(self.checkBox_lower_moves_first)
        self.checkBox_siren = QtWidgets.QCheckBox(self.frame_memorizer)
        self.checkBox_siren.setStyleSheet("color: rgb(224, 27, 36);")
        self.checkBox_siren.setObjectName("checkBox_siren")
        self.verticalLayout_4.addWidget(self.checkBox_siren)
        self.verticalLayout_6.addWidget(self.frame_memorizer)
        self.frame_config = QtWidgets.QFrame(self.frame)
        self.frame_config.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_config.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_config.setObjectName("frame_config")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_config)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_config)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.verticalLayout_6.addWidget(self.frame_config)
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout_6.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout_6.addWidget(self.pushButton_cancel)
        self.horizontalLayout.addWidget(self.frame)
        self.corner_and_inventory_select = DetectorsSelect(settings)
        self.corner_and_inventory_select.setObjectName("corner_and_inventory_select")
        self.horizontalLayout.addWidget(self.corner_and_inventory_select)

        self.retranslateUi(settings)
        self.image_getter_select.element_changed['QVariant'].connect(settings.on_image_getter_changed) # type: ignore
        self.photo_drop.received_content['QVariant'].connect(settings.on_photo_input) # type: ignore
        self.video_drop.received_content['QVariant'].connect(settings.on_video_input) # type: ignore
        self.memorizer_select.element_changed['QVariant'].connect(settings.on_memorizer_changed) # type: ignore
        self.corner_and_inventory_select.splitter_changed['QVariant'].connect(settings.on_splitter_changed) # type: ignore
        self.checkBox_lower_moves_first.clicked['bool'].connect(settings.on_lower_moves_first_switched) # type: ignore
        self.cam_id_select.element_changed['QVariant'].connect(settings.on_cam_id_changed) # type: ignore
        self.checkBox_siren.clicked['bool'].connect(settings.on_alarm_switched) # type: ignore
        self.pushButton_ok.clicked.connect(settings.on_ok_clicked) # type: ignore
        self.pushButton_cancel.clicked.connect(settings.on_cancel_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Settings"))
        self.label_4.setText(_translate("settings", "Memorizer"))
        self.checkBox_lower_moves_first.setText(_translate("settings", "Lower moves  first"))
        self.checkBox_siren.setText(_translate("settings", "Use siren (LOUD)"))
        self.label_3.setText(_translate("settings", "Config"))
        self.pushButton_ok.setText(_translate("settings", "OK"))
        self.pushButton_cancel.setText(_translate("settings", "Cancel"))
from GUI.widgets.DescriptiveComboBox import DescriptiveComboBox
from GUI.widgets.DetectorsSelect import DetectorsSelect
from GUI.widgets.FileDragDrop import FileDragDrop
