# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScanImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scan_image(object):
    def setupUi(self, scan_image):
        scan_image.setObjectName("scan_image")
        scan_image.resize(942, 583)
        self.horizontalLayout = QtWidgets.QHBoxLayout(scan_image)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(scan_image)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_settings = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_settings.setFont(font)
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.verticalLayout.addWidget(self.pushButton_settings)
        self.label_full_image = ImageLabel(self.frame_4)
        self.label_full_image.setObjectName("label_full_image")
        self.verticalLayout.addWidget(self.label_full_image)
        self.frame_video_control = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_video_control.sizePolicy().hasHeightForWidth())
        self.frame_video_control.setSizePolicy(sizePolicy)
        self.frame_video_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_control.setObjectName("frame_video_control")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_video_control)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_pause = QtWidgets.QPushButton(self.frame_video_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pause.sizePolicy().hasHeightForWidth())
        self.pushButton_pause.setSizePolicy(sizePolicy)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_3.addWidget(self.pushButton_pause)
        self.pushButton_restart_video = QtWidgets.QPushButton(self.frame_video_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_restart_video.sizePolicy().hasHeightForWidth())
        self.pushButton_restart_video.setSizePolicy(sizePolicy)
        self.pushButton_restart_video.setObjectName("pushButton_restart_video")
        self.horizontalLayout_3.addWidget(self.pushButton_restart_video)
        self.verticalLayout.addWidget(self.frame_video_control)
        self.horizontalLayout.addWidget(self.frame_4)
        self.board_view = BoardView(scan_image)
        self.board_view.setObjectName("board_view")
        self.horizontalLayout.addWidget(self.board_view)
        self.frame_memorizer = QtWidgets.QFrame(scan_image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_memorizer.sizePolicy().hasHeightForWidth())
        self.frame_memorizer.setSizePolicy(sizePolicy)
        self.frame_memorizer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_memorizer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_memorizer.setObjectName("frame_memorizer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_memorizer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_clear_memorizer = QtWidgets.QPushButton(self.frame_memorizer)
        self.pushButton_clear_memorizer.setObjectName("pushButton_clear_memorizer")
        self.verticalLayout_2.addWidget(self.pushButton_clear_memorizer)
        self.label_memorizer_status = QtWidgets.QLabel(self.frame_memorizer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_memorizer_status.sizePolicy().hasHeightForWidth())
        self.label_memorizer_status.setSizePolicy(sizePolicy)
        self.label_memorizer_status.setObjectName("label_memorizer_status")
        self.verticalLayout_2.addWidget(self.label_memorizer_status)
        self.kif_recorder = KifRecorder(self.frame_memorizer)
        self.kif_recorder.setObjectName("kif_recorder")
        self.verticalLayout_2.addWidget(self.kif_recorder)
        self.horizontalLayout.addWidget(self.frame_memorizer)

        self.retranslateUi(scan_image)
        self.pushButton_pause.clicked.connect(scan_image.on_pause_clicked) # type: ignore
        self.pushButton_restart_video.clicked.connect(scan_image.on_restart_video_clicked) # type: ignore
        self.pushButton_settings.clicked.connect(scan_image.on_settings_clicked) # type: ignore
        self.pushButton_clear_memorizer.clicked.connect(scan_image.on_clear_memorizer_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(scan_image)

    def retranslateUi(self, scan_image):
        _translate = QtCore.QCoreApplication.translate
        scan_image.setWindowTitle(_translate("scan_image", "ScanImage"))
        self.pushButton_settings.setText(_translate("scan_image", "Settings"))
        self.label_full_image.setText(_translate("scan_image", "Original image"))
        self.pushButton_pause.setText(_translate("scan_image", "Pause"))
        self.pushButton_restart_video.setText(_translate("scan_image", "Restart video"))
        self.pushButton_clear_memorizer.setText(_translate("scan_image", "Clear memorizer"))
        self.label_memorizer_status.setText(_translate("scan_image", "Memorizer status"))
from GUI.widgets.BoardView import BoardView
from GUI.widgets.ImageLabel import ImageLabel
from GUI.widgets.KifRecorder import KifRecorder
