# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UploadFileDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 246)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_file_type = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_file_type.setFont(font)
        self.label_file_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_file_type.setObjectName("label_file_type")
        self.verticalLayout.addWidget(self.label_file_type)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_paste = QtWidgets.QPushButton(Dialog)
        self.pushButton_paste.setObjectName("pushButton_paste")
        self.verticalLayout.addWidget(self.pushButton_paste)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pushButton_search = QtWidgets.QPushButton(Dialog)
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout.addWidget(self.pushButton_search)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        self.pushButton_paste.clicked.connect(Dialog.on_paste_clicked) # type: ignore
        self.pushButton_search.clicked.connect(Dialog.on_search_clicked) # type: ignore
        self.pushButton.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Upload files"))
        self.label_file_type.setText(_translate("Dialog", "File type: "))
        self.label.setText(_translate("Dialog", "Drag and drop files here"))
        self.label_2.setText(_translate("Dialog", "or"))
        self.pushButton_paste.setText(_translate("Dialog", "Paste from clipboard"))
        self.label_3.setText(_translate("Dialog", "or"))
        self.pushButton_search.setText(_translate("Dialog", "Search for file..."))
        self.label_4.setText(_translate("Dialog", "or"))
        self.pushButton.setText(_translate("Dialog", "Cancel"))
