# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualCornerSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_visualCornerSelect(object):
    def setupUi(self, visualCornerSelect):
        visualCornerSelect.setObjectName("visualCornerSelect")
        visualCornerSelect.resize(556, 359)
        self.verticalLayout = QtWidgets.QVBoxLayout(visualCornerSelect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(visualCornerSelect)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label_original = ImageLabel(self.frame_2)
        self.image_label_original.setObjectName("image_label_original")
        self.horizontalLayout.addWidget(self.image_label_original)
        self.image_label_no_perspective = ImageLabel(self.frame_2)
        self.image_label_no_perspective.setObjectName("image_label_no_perspective")
        self.horizontalLayout.addWidget(self.image_label_no_perspective)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(visualCornerSelect)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.corner_detector_select = DescriptiveComboBox(self.frame)
        self.corner_detector_select.setObjectName("corner_detector_select")
        self.verticalLayout_2.addWidget(self.corner_detector_select)
        self.pushButton_set_corners = QtWidgets.QPushButton(self.frame)
        self.pushButton_set_corners.setObjectName("pushButton_set_corners")
        self.verticalLayout_2.addWidget(self.pushButton_set_corners)
        self.inventory_detector_select = DescriptiveComboBox(self.frame)
        self.inventory_detector_select.setObjectName("inventory_detector_select")
        self.verticalLayout_2.addWidget(self.inventory_detector_select)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(visualCornerSelect)
        self.image_label_original.clicked.connect(visualCornerSelect.on_image_clicked) # type: ignore
        self.pushButton_set_corners.clicked.connect(visualCornerSelect.on_set_corners_clicked) # type: ignore
        self.corner_detector_select.element_changed['QVariant'].connect(visualCornerSelect.on_corner_detector_changed) # type: ignore
        self.inventory_detector_select.element_changed['QVariant'].connect(visualCornerSelect.on_inventory_detector_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(visualCornerSelect)

    def retranslateUi(self, visualCornerSelect):
        _translate = QtCore.QCoreApplication.translate
        visualCornerSelect.setWindowTitle(_translate("visualCornerSelect", "visualCornerSelect"))
        self.image_label_original.setText(_translate("visualCornerSelect", "Image"))
        self.image_label_no_perspective.setText(_translate("visualCornerSelect", "Image"))
        self.pushButton_set_corners.setText(_translate("visualCornerSelect", "Set Corners"))
from GUI.components.DescriptiveComboBox import DescriptiveComboBox
from GUI.components.ImageLabel import ImageLabel
